iartemis:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_front_left_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_front_right_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_rear_left_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_rear_right_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_middle_left_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: middle_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_middle_right_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: middle_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_front_triangle_base_to_front_right_direction_axis_controller:
    type: effort_controllers/JointPositionController
    joint: front_triangle_base_to_front_right_direction_axis
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_rear_triangle_base_to_rear_right_direction_axis_controller:
    type: effort_controllers/JointPositionController
    joint: rear_triangle_base_to_rear_right_direction_axis
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_ptu_pan_controller:
    type: effort_controllers/JointPositionController
    joint: turret_arm_to_ptu_pan
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_ptu_tilt_controller:
    type: effort_controllers/JointPositionController
    joint: ptu_pan_to_middle_ptu_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}
